#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile.ssl for crypto/cversion.c */
  #define CFLAGS "arm-linux-gnueabihf-gcc -DNO_ASM -DL_ENDIAN -DTERMIO -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "linux-arm"
  #define DATE "Sun 13 Oct 2024 15:25:48 EEST"
#endif
